# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagesascii', '0003_auto_20160608_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asciiimage',
            name='ascii_art',
        ),
    ]
